/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.filemgmt.views;

import com.rameses.osiris2.themes.OKCancelPage;
import com.rameses.rcp.ui.annotations.Template;
import java.awt.Dimension;

/**
 *
 * @author ramesesinc
 */
@Template(OKCancelPage.class)
public class FileUploadTaskPage extends javax.swing.JPanel { 

    /**
     * Creates new form FileUploadTaskPage
     */
    public FileUploadTaskPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xLabel1 = new com.rameses.rcp.control.XLabel();
        fileUploadPanel1 = new com.rameses.filemgmt.components.FileUploadPanel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setPreferredSize(new java.awt.Dimension(575, 200));
        setLayout(new java.awt.BorderLayout());

        xLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 10, 0));
        xLabel1.setFontStyle("font-size: 14; font-weight: bold;");
        xLabel1.setForeground(new java.awt.Color(80, 80, 80));
        xLabel1.setText("Uploading Files");
        add(xLabel1, java.awt.BorderLayout.PAGE_START);

        fileUploadPanel1.setDepends(new String[] {"files"});
        fileUploadPanel1.setHandler("uploadHandler");
        add(fileUploadPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.filemgmt.components.FileUploadPanel fileUploadPanel1;
    private com.rameses.rcp.control.XLabel xLabel1;
    // End of variables declaration//GEN-END:variables
}
