/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.filemgmt.components;

/**
 *
 * @author ramesesinc
 */
public class BasicFileViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form BasicFileViewPanel
     */
    public BasicFileViewPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        thumbnailViewPanel1 = new com.rameses.filemgmt.components.ThumbnailViewPanel();

        setMinimumSize(new java.awt.Dimension(200, 200));
        setLayout(new java.awt.BorderLayout());

        thumbnailViewPanel1.setName("selectedThumbnail"); // NOI18N
        thumbnailViewPanel1.setCellSize(new java.awt.Dimension(100, 90));
        thumbnailViewPanel1.setHandler("thumbnailListHandler");
        add(thumbnailViewPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.filemgmt.components.ThumbnailViewPanel thumbnailViewPanel1;
    // End of variables declaration//GEN-END:variables
}
